# Generated by Django 5.0.6 on 2024-05-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_masters_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweets',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
