# Generated by Django 5.0.6 on 2024-05-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_sweets_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweets',
            name='price',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweets',
            name='price_type',
            field=models.CharField(choices=[('$', 'Usd'), ('sum', 'Sum')], default='$', max_length=10),
        ),
    ]
