# Generated by Django 5.0.6 on 2024-05-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_sweets_price_sweets_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='message',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
