# Generated by Django 5.0.6 on 2024-05-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_discounts_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='discount_price',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discounts',
            name='sweet',
            field=models.ManyToManyField(blank=True, to='cakes.sweets'),
        ),
    ]
