# Generated by Django 5.0.6 on 2024-05-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_discounts_discount_price_alter_discounts_sweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='discounts',
            name='price',
            field=models.CharField(default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
