# Generated by Django 5.0.6 on 2024-05-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_discounts_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masters',
            name='type',
        ),
        migrations.AddField(
            model_name='masters',
            name='static',
            field=models.CharField(choices=[('df,', 'Draft'), ('pb', 'Published')], default='df,', max_length=20),
        ),
    ]
