# Generated by Django 5.0.6 on 2024-05-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0009_remove_masters_type_masters_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masters',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
