# Generated by Django 5.0.6 on 2024-05-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0010_masters_slug_masters_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='masters',
            name='search',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
